{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tuneperfect.fullname" . }}-coturn-config
  namespace: {{ .Release.Namespace }}
data:
  STUN_URL: "stun:{{ .Values.coturn.realm }}:{{ .Values.coturn.listeningPort }}"
  TURN_URL: "turn:{{ .Values.coturn.realm }}:{{ .Values.coturn.listeningPort }}"
{{- end }}
